# Generated by Django 5.0.6 on 2024-05-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_join',
            new_name='date_joined',
        ),
    ]
