# Generated by Django 5.0.6 on 2024-05-17 22:27

import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('genero', models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Feminino'), ('OTR', 'Outro')], max_length=9)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(max_length=15, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('municipio', models.CharField(max_length=20, verbose_name='Municipio')),
                ('unidade_federal', models.CharField(max_length=2, verbose_name='Unidade Federal')),
                ('data_nacimento', models.DateField(verbose_name='Data de Nacimento')),
                ('data_inicio', models.DateField(verbose_name='Data de Inicio')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Está ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(max_length=200, verbose_name='Convenio')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(max_length=30, verbose_name='Plano')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoCoberto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=200, verbose_name='Serviços')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
