# Generated by Django 5.0.6 on 2024-05-22 13:41

import django.core.validators
import django.db.models.deletion
import django_cpf_cnpj.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(max_length=200, verbose_name='Convenio')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoCoberto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=200, verbose_name='Serviços')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='Sobremone')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=50, unique=True, verbose_name='CPF')),
                ('genero', models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Feminino'), ('OTR', 'Outro')], max_length=9, verbose_name='Genero')),
                ('telefone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="O número precisa estar neste formato:                         '+99 99 9999-0000'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(max_length=15, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('municipio', models.CharField(max_length=20, verbose_name='Municipio')),
                ('unidade_federal', models.CharField(max_length=2, verbose_name='Unidade Federal')),
                ('data_nacimento', models.DateField(verbose_name='Data de Nacimento')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Inicio')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='funcionarios.agenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(max_length=30, verbose_name='Plano')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_convenio', to='clientes.convenio')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.planoconvenio'),
        ),
        migrations.CreateModel(
            name='ServicoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.ManyToManyField(related_name='servico_plano', to='clientes.planoconvenio')),
                ('servico', models.ManyToManyField(related_name='serviço_plano', to='clientes.servicocoberto')),
            ],
        ),
    ]
