# Generated by Django 5.0.6 on 2024-05-17 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.convenio'),
        ),
        migrations.AddField(
            model_name='planoconvenio',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_convenio', to='clientes.convenio'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.planoconvenio'),
        ),
        migrations.AddField(
            model_name='servicoplano',
            name='plano',
            field=models.ManyToManyField(related_name='servico_plano', to='clientes.planoconvenio'),
        ),
        migrations.AddField(
            model_name='servicoplano',
            name='servico',
            field=models.ManyToManyField(related_name='serviço_plano', to='clientes.servicocoberto'),
        ),
    ]
