# Generated by Django 5.0.6 on 2024-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_inicio',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Inicio'),
        ),
    ]
