# Generated by Django 5.0.6 on 2024-05-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='last_name',
            new_name='sobrenome',
        ),
    ]
