# Generated by Django 5.0.6 on 2024-05-21 08:02

import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Feminino'), ('OTR', 'Outro')], max_length=9, verbose_name='Genero'),
        ),
    ]
