# Generated by Django 5.0.6 on 2024-06-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_telefone'),
        ('funcionarios', '0003_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('agenda', 'cliente')},
        ),
    ]
