# Generated by Django 5.0.4 on 2024-04-23 00:33

import django.core.validators
import django.db.models.deletion
import django_cpf_cnpj.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=200, unique=True, verbose_name='Especialidades')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('municipio', models.CharField(max_length=20, verbose_name='Municipio')),
                ('unidade_federal', models.CharField(max_length=2, verbose_name='Unidade Federal')),
                ('complemento', models.CharField(blank=True, max_length=200, verbose_name='Complemento')),
                ('data_nacimento', models.DateField(verbose_name='Data de Nacimento')),
                ('data_contratacao', models.DateField(verbose_name='Data de contratação')),
                ('is_medico', models.BooleanField(default=False, verbose_name='É medico')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('crm', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid_crm', message="O CRM precisa estar no seguinte formato:                                 'xxxxxxx-UF'", regex='^\\d{7}-\\d{2}$')], verbose_name='CRM')),
                ('especialidade_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='funcionarios.especialidade')),
                ('funcionario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcioanrios', to='funcionarios.funcionario')),
            ],
        ),
    ]
