# Generated by Django 5.0.6 on 2024-05-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='telefone',
        ),
    ]
