# Generated by Django 5.0.6 on 2024-05-22 07:00

import django_cpf_cnpj.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=50, unique=True, verbose_name='CPF'),
        ),
    ]
