# Generated by Django 5.0.6 on 2024-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_servico_rename_especialidade_id_medico_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(max_length=30, verbose_name='Genero'),
        ),
    ]
