# Generated by Django 5.0.6 on 2024-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='last_name',
            new_name='sobrenome',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.TimeField(max_length=10, verbose_name='Horario'),
        ),
    ]
