# Generated by Django 5.0.6 on 2024-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_agenda_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[('1', '09:00'), ('2', '09:30'), ('3', '10:00'), ('4', '10:30'), ('5', '11:00'), ('6', '11:30'), ('7', '12:00'), ('8', '12:30'), ('9', '13:00'), ('10', '13:30'), ('11', '14:00'), ('12', '14:30'), ('13', '15:00'), ('14', '15:30'), ('15', '16:00'), ('16', '16:30'), ('17', '17:30'), ('18', '17:30'), ('19', '18:00')], max_length=10),
        ),
    ]
